# Generated by Django 6.0.7 on 2026-07-27 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_flight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_FLIGHT', 'In flight'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=20),
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate_number', models.CharField(max_length=10)),
                ('terminal', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('MAINTENANCE', 'Maintenance'), ('CLOSED', 'Closed')], default='AVAILABLE', max_length=20)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gates', to='flights.airport')),
            ],
        ),
    ]
