# Generated by Django 6.0.7 on 2026-07-27 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_alter_aircraft_status_gate'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='gate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.gate'),
        ),
    ]
