# Generated by Django 6.0.7 on 2026-08-03 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0009_checkin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baggage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag_tag_number', models.CharField(max_length=30, unique=True)),
                ('bag_type', models.CharField(choices=[('CHECKED', 'Checked'), ('CARRY_ON', 'Carry-On'), ('OVERSIZED', 'Oversized')], default='CHECKED', max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('CHECKED', 'Checked'), ('LOADED', 'Loaded'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED', 'Arrived'), ('CLAIMED', 'Claimed'), ('LOST', 'Lost')], default='CHECKED', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('check_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baggage', to='flights.checkin')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arriving_baggage', to='flights.airport')),
            ],
        ),
    ]
