# Generated by Django 6.0.7 on 2026-08-03 09:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0010_baggage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boarding_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('BOARDED', 'Boarded'), ('NO_SHOW', 'No Show'), ('DENIED', 'Denied Boarding')], default='WAITING', max_length=20)),
                ('boarded_by', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('check_in', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boarding', to='flights.checkin')),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boardings', to='flights.gate')),
            ],
        ),
    ]
