# Generated by Django 6.0.7 on 2026-08-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0011_boarding'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('employee_number', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(choices=[('PILOT', 'Pilot'), ('COPILOT', 'Co-Pilot'), ('CABIN_CREW', 'Cabin Crew')], max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
