# Generated by Django 6.0.7 on 2026-08-06 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0013_crewassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Runway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runway_code', models.CharField(max_length=10, unique=True)),
                ('length_meters', models.PositiveIntegerField()),
                ('width_meters', models.PositiveIntegerField()),
                ('surface_type', models.CharField(default='Asphalt', max_length=30)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('MAINTENANCE', 'Under Maintenance'), ('CLOSED', 'Closed')], default='AVAILABLE', max_length=20)),
                ('lighting_available', models.BooleanField(default=True)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runways', to='flights.airport')),
            ],
        ),
    ]
